// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.5
// source: loadbalancing/internal/pkg/proto/lookaside/lookaside.proto

package lookaside

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request_RouterType int32

const (
	Request_RANDOM     Request_RouterType = 0
	Request_ROUNDROBIN Request_RouterType = 1
)

// Enum value maps for Request_RouterType.
var (
	Request_RouterType_name = map[int32]string{
		0: "RANDOM",
		1: "ROUNDROBIN",
	}
	Request_RouterType_value = map[string]int32{
		"RANDOM":     0,
		"ROUNDROBIN": 1,
	}
)

func (x Request_RouterType) Enum() *Request_RouterType {
	p := new(Request_RouterType)
	*p = x
	return p
}

func (x Request_RouterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_RouterType) Descriptor() protoreflect.EnumDescriptor {
	return file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_enumTypes[0].Descriptor()
}

func (Request_RouterType) Type() protoreflect.EnumType {
	return &file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_enumTypes[0]
}

func (x Request_RouterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_RouterType.Descriptor instead.
func (Request_RouterType) EnumDescriptor() ([]byte, []int) {
	return file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescGZIP(), []int{0, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Router    Request_RouterType `protobuf:"varint,1,opt,name=router,proto3,enum=lookaside.Request_RouterType" json:"router,omitempty"`
	Service   string             `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Namespace string             `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRouter() Request_RouterType {
	if x != nil {
		return x.Router
	}
	return Request_RANDOM
}

func (x *Request) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Request) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto protoreflect.FileDescriptor

var file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x6f, 0x6b, 0x61, 0x73, 0x69, 0x64, 0x65, 0x2f, 0x6c, 0x6f, 0x6f,
	0x6b, 0x61, 0x73, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x6f,
	0x6f, 0x6b, 0x61, 0x73, 0x69, 0x64, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6c, 0x6f, 0x6f, 0x6b, 0x61, 0x73, 0x69, 0x64, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x22, 0x28, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x52, 0x4f, 0x55, 0x4e, 0x44, 0x52, 0x4f, 0x42, 0x49, 0x4e, 0x10, 0x01, 0x22, 0x24, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x32, 0x41, 0x0a, 0x09, 0x4c, 0x6f, 0x6f, 0x6b, 0x61, 0x73, 0x69, 0x64, 0x65, 0x12,
	0x34, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x12, 0x12, 0x2e, 0x6c, 0x6f, 0x6f,
	0x6b, 0x61, 0x73, 0x69, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x6c, 0x6f, 0x6f, 0x6b, 0x61, 0x73, 0x69, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x6f, 0x6f, 0x6b, 0x61,
	0x73, 0x69, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescOnce sync.Once
	file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescData = file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDesc
)

func file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescGZIP() []byte {
	file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescOnce.Do(func() {
		file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescData = protoimpl.X.CompressGZIP(file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescData)
	})
	return file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDescData
}

var file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_goTypes = []interface{}{
	(Request_RouterType)(0), // 0: lookaside.Request.RouterType
	(*Request)(nil),         // 1: lookaside.Request
	(*Response)(nil),        // 2: lookaside.Response
}
var file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_depIdxs = []int32{
	0, // 0: lookaside.Request.router:type_name -> lookaside.Request.RouterType
	1, // 1: lookaside.Lookaside.Resolve:input_type -> lookaside.Request
	2, // 2: lookaside.Lookaside.Resolve:output_type -> lookaside.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_init() }
func file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_init() {
	if File_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_goTypes,
		DependencyIndexes: file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_depIdxs,
		EnumInfos:         file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_enumTypes,
		MessageInfos:      file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_msgTypes,
	}.Build()
	File_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto = out.File
	file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_rawDesc = nil
	file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_goTypes = nil
	file_loadbalancing_internal_pkg_proto_lookaside_lookaside_proto_depIdxs = nil
}
