// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: loadbalancing/internal/pkg/proto/lookaside/lookaside.proto

package lookaside

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LookasideClient is the client API for Lookaside service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LookasideClient interface {
	Resolve(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type lookasideClient struct {
	cc grpc.ClientConnInterface
}

func NewLookasideClient(cc grpc.ClientConnInterface) LookasideClient {
	return &lookasideClient{cc}
}

func (c *lookasideClient) Resolve(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/lookaside.Lookaside/Resolve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LookasideServer is the server API for Lookaside service.
// All implementations must embed UnimplementedLookasideServer
// for forward compatibility
type LookasideServer interface {
	Resolve(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedLookasideServer()
}

// UnimplementedLookasideServer must be embedded to have forward compatible implementations.
type UnimplementedLookasideServer struct {
}

func (UnimplementedLookasideServer) Resolve(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedLookasideServer) mustEmbedUnimplementedLookasideServer() {}

// UnsafeLookasideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LookasideServer will
// result in compilation errors.
type UnsafeLookasideServer interface {
	mustEmbedUnimplementedLookasideServer()
}

func RegisterLookasideServer(s grpc.ServiceRegistrar, srv LookasideServer) {
	s.RegisterService(&Lookaside_ServiceDesc, srv)
}

func _Lookaside_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookasideServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lookaside.Lookaside/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookasideServer).Resolve(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Lookaside_ServiceDesc is the grpc.ServiceDesc for Lookaside service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lookaside_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lookaside.Lookaside",
	HandlerType: (*LookasideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Lookaside_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadbalancing/internal/pkg/proto/lookaside/lookaside.proto",
}
