FROM golang:1.16 AS builder
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o grpc-client cmd/book-client/main.go



FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/grpc-client .
CMD ["./grpc-client"]
