// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: proto/fibonacci.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FibonacciServiceClient is the client API for FibonacciService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibonacciServiceClient interface {
	// Unary
	SyncFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (*SyncFibonacciResponse, error)
	// Server Streaming
	AsyncFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (FibonacciService_AsyncFibonacciClient, error)
}

type fibonacciServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFibonacciServiceClient(cc grpc.ClientConnInterface) FibonacciServiceClient {
	return &fibonacciServiceClient{cc}
}

func (c *fibonacciServiceClient) SyncFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (*SyncFibonacciResponse, error) {
	out := new(SyncFibonacciResponse)
	err := c.cc.Invoke(ctx, "/proto.FibonacciService/SyncFibonacci", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibonacciServiceClient) AsyncFibonacci(ctx context.Context, in *FibonacciRequest, opts ...grpc.CallOption) (FibonacciService_AsyncFibonacciClient, error) {
	stream, err := c.cc.NewStream(ctx, &FibonacciService_ServiceDesc.Streams[0], "/proto.FibonacciService/AsyncFibonacci", opts...)
	if err != nil {
		return nil, err
	}
	x := &fibonacciServiceAsyncFibonacciClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FibonacciService_AsyncFibonacciClient interface {
	Recv() (*AsyncFibonacciResponse, error)
	grpc.ClientStream
}

type fibonacciServiceAsyncFibonacciClient struct {
	grpc.ClientStream
}

func (x *fibonacciServiceAsyncFibonacciClient) Recv() (*AsyncFibonacciResponse, error) {
	m := new(AsyncFibonacciResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FibonacciServiceServer is the server API for FibonacciService service.
// All implementations must embed UnimplementedFibonacciServiceServer
// for forward compatibility
type FibonacciServiceServer interface {
	// Unary
	SyncFibonacci(context.Context, *FibonacciRequest) (*SyncFibonacciResponse, error)
	// Server Streaming
	AsyncFibonacci(*FibonacciRequest, FibonacciService_AsyncFibonacciServer) error
	mustEmbedUnimplementedFibonacciServiceServer()
}

// UnimplementedFibonacciServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFibonacciServiceServer struct {
}

func (UnimplementedFibonacciServiceServer) SyncFibonacci(context.Context, *FibonacciRequest) (*SyncFibonacciResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncFibonacci not implemented")
}
func (UnimplementedFibonacciServiceServer) AsyncFibonacci(*FibonacciRequest, FibonacciService_AsyncFibonacciServer) error {
	return status.Errorf(codes.Unimplemented, "method AsyncFibonacci not implemented")
}
func (UnimplementedFibonacciServiceServer) mustEmbedUnimplementedFibonacciServiceServer() {}

// UnsafeFibonacciServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibonacciServiceServer will
// result in compilation errors.
type UnsafeFibonacciServiceServer interface {
	mustEmbedUnimplementedFibonacciServiceServer()
}

func RegisterFibonacciServiceServer(s grpc.ServiceRegistrar, srv FibonacciServiceServer) {
	s.RegisterService(&FibonacciService_ServiceDesc, srv)
}

func _FibonacciService_SyncFibonacci_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibonacciRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibonacciServiceServer).SyncFibonacci(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FibonacciService/SyncFibonacci",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibonacciServiceServer).SyncFibonacci(ctx, req.(*FibonacciRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FibonacciService_AsyncFibonacci_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FibonacciRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FibonacciServiceServer).AsyncFibonacci(m, &fibonacciServiceAsyncFibonacciServer{stream})
}

type FibonacciService_AsyncFibonacciServer interface {
	Send(*AsyncFibonacciResponse) error
	grpc.ServerStream
}

type fibonacciServiceAsyncFibonacciServer struct {
	grpc.ServerStream
}

func (x *fibonacciServiceAsyncFibonacciServer) Send(m *AsyncFibonacciResponse) error {
	return x.ServerStream.SendMsg(m)
}

// FibonacciService_ServiceDesc is the grpc.ServiceDesc for FibonacciService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FibonacciService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FibonacciService",
	HandlerType: (*FibonacciServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncFibonacci",
			Handler:    _FibonacciService_SyncFibonacci_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AsyncFibonacci",
			Handler:       _FibonacciService_AsyncFibonacci_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/fibonacci.proto",
}
